# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'travelcar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for travelcar
  pod 'Alamofire', '4.9.0'
  pod 'AlamofireImage', '~> 3.5'

end
